version: '3'

services:
  web:
    build: ./Rental
    env_file:
      - .env
    volumes:
      - ./Rental:/Rental
    ports:
      - "8000:8000"
    depends_on:
      - db


  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: